<?php $clockConfig = $block->getClockConfig() ?>
<div class="digital-clock">00:00:00</div>

<style>
    .digital-clock {
        margin: auto;
        position: absolute;
        top: 0;
        left: 0;
        bottom: 0;
        right: 0;
        width: <?= $clockConfig['size']['width'] ?>px;
        height: 60px;
        color: #ffffff;
        border: 2px solid #999;
        border-radius: 4px;
        text-align: center;
        font: <?= $clockConfig['size']['font-width'] ?>px/60px 'DIGITAL', Helvetica;
    }
</style>
<script>
    require(['jquery'],function ($) {
        $(document).ready(function() {
            clockUpdate();
            setInterval(clockUpdate, 1000);
        });

        function clockUpdate() {
            var date = new Date();
            $('.digital-clock').css({'color': '<?= $clockConfig['clockTextColor'] ?>', 'text-shadow': '0 0 6px #ff0','background': '<?= $clockConfig['clockColor'] ?>'});
            function addZero(x) {
                if (x < 10) {
                    return x = '0' + x;
                } else {
                    return x;
                }
            }

            function twelveHour(x) {
                if (x > 12) {
                    return x = x - 12;
                } else if (x == 0) {
                    return x = 12;
                } else {
                    return x;
                }
            }

            var h = addZero(twelveHour(date.getHours()));
            var m = addZero(date.getMinutes());
            var s = addZero(date.getSeconds());

            $('.digital-clock').text(h + ':' + m + ':' + s)
        }
    })
</script>