<?php
$render = $block->loadTable();
?>

<fieldset class="fieldset">
    <legend>Table</legend>
    <div class="field">
        <table class="table-secondary">
            <thead>
                <tr>
                    <th class="data-grid-th no-link col-rule_title">Title</th>
                    <th class="data-grid-th no-link col-rule_status">Status</th>
                    <th class="data-grid-th no-link col-rule_type">Rule Type</th>
                    <th class="data-grid-th no-link col-rule_conditions">Conditions Serialized</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($render as $value) :?>
                <tr>
                    <td class="col-rule_title"><?= $value['title'] ?></td>
                    <td class="col-rule_status"><?= $value['status'] ?></td>
                    <td class="col-rule_type"><?= $value['rule_type'] ?></td>
                    <td class="col-rule_conditions"><?= $value['conditions_serialized'] ?></td>
                </tr>
                <?php endforeach;?>
            </tbody>
        </table>
    </div>
</fieldset>